name: build-deploy

on: workflow_dispatch

env:
  AZURE_RESOURCEGROUP_NAME: RG_ACGResume
  AZURE_FUNCTIONAPP_NAME: resume-functions  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/ResumeFunction'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'              # set this to the dotnet version to use


jobs:
  deploy-arm-template:
    runs-on: ubuntu-latest
    steps:
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Depoy ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./deploy/main.json

  azure-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
